"""
app/services/attendance_service.py
───────────────────────────────────────────────────────────────────────────────
Business logic for real-time face recognition and attendance marking.

Orchestrates:
  • FaceDetector       — detect faces in incoming frames
  • EmbeddingGenerator — generate 512-D FaceNet vectors
  • SimilarityService  — compute cosine similarity and classify confidence
  • EmbeddingRepository — pgvector nearest-neighbour search
  • AttendanceRepository — CRUD + duplicate prevention + analytics queries

Recognition pipeline (mirrors desktop app's RecognitionResult flow):
  1. Detect face in frame             (FaceDetector)
  2. Generate 512-D embedding         (EmbeddingGenerator)
  3. Nearest-neighbour search         (pgvector via EmbeddingRepository)
  4. Cosine similarity threshold      (SimilarityService)
  5. Mark attendance if above threshold and not already marked today
     (AttendanceRepository)

Status derivation (automatic — never caller-supplied):
  • Present : recognised from CHECKIN_START through CHECKIN_LATE.
  • Late    : recognised from CHECKIN_LATE through CHECKIN_CLOSE.
  • Absent  : generated by generate_absent_records_for_date() at end-of-day
              for every registered student with no recognition record that day.

Analytics:
  • AnalyticsSummary          — dashboard stat cards
  • DailyAttendanceResponse   — daily bar chart data
  • StudentAttendanceFrequency — per-person bar chart data
  • MonthlyAttendanceResponse  — monthly bar chart data
───────────────────────────────────────────────────────────────────────────────
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date as date_, datetime, time as time_, timedelta
from functools import lru_cache
from typing import Sequence
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError

import numpy as np
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import settings
from app.core.logging import get_logger
from app.ml.embedding_generator import EmbeddingGenerator
from app.ml.face_detector import FaceDetector
from app.ml.similarity import SimilarityService, SimilarityThresholds
from app.models.attendance import AttendanceRecord, AttendanceStatus, ConfidenceBand
from app.models.student import Student
from app.repositories.attendance_repo import AttendanceRepository
from app.repositories.embedding_repo import EmbeddingRepository
from app.repositories.student_repo import StudentRepository
from app.schemas.attendance import (
    AttendanceListResponse,
    AttendanceMarkResponse,
    AttendanceQueryParams,
    AttendanceRead,
    AttendanceReadWithStudent,
)
from app.schemas.analytics import (
    AnalyticsSummary,
    DailyAttendancePoint,
    DailyAttendanceResponse,
    MonthlyAttendancePoint,
    MonthlyAttendanceResponse,
    StudentAttendanceFrequency,
    StudentAttendanceFrequencyResponse,
)

log = get_logger(__name__)

ATTENDANCE_WINDOW_NOT_STARTED_MESSAGE = "Attendance window has not started."


@lru_cache(maxsize=1)
def _attendance_timezone() -> ZoneInfo | None:
    """
    Resolve the configured attendance timezone once per process.

    If IANA timezone data is not installed on the host, fall back to the
    server's local timezone instead of breaking recognition or scheduling.
    """
    try:
        return ZoneInfo(settings.ATTENDANCE_TIMEZONE)
    except ZoneInfoNotFoundError:
        log.warning(
            "Configured attendance timezone not found; using server local timezone",
            extra={"ctx_timezone": settings.ATTENDANCE_TIMEZONE},
        )
        return None


@dataclass
class RecognitionResult:
    """
    Outcome of a single recognition attempt from the video pipeline.

    Mirrors the desktop app's RecognitionResult namedtuple
    (utils/similarity.py) so the rest of the codebase has a familiar shape.
    """

    recognized: bool
    student: Student | None
    similarity: float
    confidence_band: ConfidenceBand
    message: str
    attendance_marked: bool = False
    already_marked: bool = False
    blocked_by_policy: bool = False


class AttendanceServiceError(Exception):
    """Base exception for AttendanceService business-logic errors."""


class AttendanceWindowNotStartedError(AttendanceServiceError):
    """Raised when a check-in is attempted before the configured window."""


class AttendanceService:
    """
    Business-logic layer for recognition-driven attendance marking and
    analytics retrieval.

    All methods are async; commits are left to the caller.
    """

    def __init__(
        self,
        session: AsyncSession,
        *,
        face_detector: FaceDetector | None = None,
        embedding_generator: EmbeddingGenerator | None = None,
        similarity_service: SimilarityService | None = None,
        thresholds: SimilarityThresholds | None = None,
    ) -> None:
        self._session = session
        self._attendance_repo = AttendanceRepository(session)
        self._embedding_repo = EmbeddingRepository(session)
        self._student_repo = StudentRepository(session)

        self._detector = face_detector or FaceDetector()
        self._embedder = embedding_generator or EmbeddingGenerator()
        self._similarity = similarity_service or SimilarityService(
            thresholds=thresholds or SimilarityThresholds()
        )

    # ── Status derivation (single source of truth) ────────────────────────

    @staticmethod
    def _plain_time(value: time_) -> time_:
        """Return a timezone-free time value for HH:MM policy comparisons."""
        return value.replace(tzinfo=None)

    @staticmethod
    def _attendance_now() -> datetime:
        """Return the current datetime in the configured attendance timezone."""
        tz = _attendance_timezone()
        if tz is None:
            return datetime.now().astimezone()
        return datetime.now(tz)

    @staticmethod
    def _time_in_range(value: time_, start: time_, end: time_) -> bool:
        """
        Return True when value is in [start, end).

        Supports overnight ranges such as 20:00 -> 00:00, where values from
        20:00 through 23:59:59 are inside the range and 00:00 is outside.
        """
        if start < end:
            return start <= value < end
        if start > end:
            return value >= start or value < end
        return True

    @classmethod
    def _checkin_window_is_open(cls, at_time: time_) -> bool:
        check_time = cls._plain_time(at_time)
        return cls._time_in_range(
            check_time,
            cls._plain_time(settings.CHECKIN_START),
            cls._plain_time(settings.CHECKIN_CLOSE),
        )

    @classmethod
    def _attendance_summary_date(cls, now: datetime | None = None) -> date_:
        """
        Date shown on the admin dashboard status cards.

        Before the 20:00 window opens, the most relevant hostel attendance
        date is yesterday because midnight absence generation belongs to the
        previous attendance date.
        """
        current = now or cls._attendance_now()
        current_time = cls._plain_time(current.time())
        start = cls._plain_time(settings.CHECKIN_START)
        close = cls._plain_time(settings.CHECKIN_CLOSE)

        if start > close and current_time < close:
            return current.date() - timedelta(days=1)
        if current_time < start:
            return current.date() - timedelta(days=1)
        return current.date()

    @classmethod
    def _derive_status(cls, at_time: time_) -> AttendanceStatus:
        """
        Derive attendance status from the time of recognition.

        Rule:
          before CHECKIN_START                 -> blocked
          CHECKIN_START <= time < CHECKIN_LATE -> Present
          CHECKIN_LATE <= time < CHECKIN_CLOSE -> Late

        This is the only place in the codebase where Present/Late is
        determined.  It is called by both process_frame() and mark_manual()
        so the rule is never duplicated.
        """
        check_time = cls._plain_time(at_time)
        if not cls._checkin_window_is_open(check_time):
            raise AttendanceWindowNotStartedError(ATTENDANCE_WINDOW_NOT_STARTED_MESSAGE)

        if cls._time_in_range(
            check_time,
            cls._plain_time(settings.CHECKIN_START),
            cls._plain_time(settings.CHECKIN_LATE),
        ):
            return AttendanceStatus.PRESENT
        return AttendanceStatus.LATE

    # ── Recognition pipeline ──────────────────────────────────────────────

    async def process_frame(
        self,
        frame: np.ndarray,
        *,
        device_id: str | None = None,
        on_date: date_ | None = None,
    ) -> RecognitionResult:
        """
        Run the full recognition-and-marking pipeline on a single video frame.

        Steps:
          1. Detect face crop
          2. Generate 512-D embedding
          3. pgvector nearest-neighbour search
          4. Threshold evaluation
          5. Duplicate-attendance check
          6. Derive status from current time
          7. Mark attendance

        Args:
            frame:     BGR numpy array from OpenCV VideoCapture.
            device_id: Optional camera/kiosk identifier.
            on_date:   Date for the attendance record (defaults to today).

        Returns:
            A RecognitionResult describing the outcome — including whether
            the face was recognised, which student matched, the similarity
            score, confidence band, and a human-readable message.
        """

        # Step 1 — Face detection
        face_crop = self._detector.detect_and_crop(frame)
        if face_crop is None:
            return RecognitionResult(
                recognized=False,
                student=None,
                similarity=0.0,
                confidence_band=ConfidenceBand.LOW,
                message="No face detected in frame.",
            )

        # Step 2 — Embedding generation
        embedding_vector: list[float] = self._embedder.generate(face_crop)

        # Step 3 — Nearest-neighbour search (top 5 candidates)
        matches = await self._embedding_repo.find_nearest(embedding_vector, top_k=5)
        if not matches:
            return RecognitionResult(
                recognized=False,
                student=None,
                similarity=0.0,
                confidence_band=ConfidenceBand.LOW,
                message="No registered embeddings in database.",
            )

        # Step 4 — Evaluate against threshold
        best_match = matches[0]
        eval_result = self._similarity.evaluate(best_match.similarity)

        if not eval_result.above_threshold:
            # Face detected but below recognition threshold — do not create any
            # attendance record.  The caller (WebSocket broadcast / REST endpoint)
            # can inform the user that the face was not recognised.
            return RecognitionResult(
                recognized=False,
                student=None,
                similarity=best_match.similarity,
                confidence_band=eval_result.confidence_band,
                message=f"Face not recognised (similarity={best_match.similarity:.3f}, "
                        f"threshold={self._similarity.thresholds.recognition:.2f}).",
            )

        # Step 5 — Fetch student; if the record has been hard-deleted since
        # the embedding was stored, the nearest-neighbour hit is stale.
        student_id = best_match.embedding.student_id
        student = await self._student_repo.get_by_id(student_id)
        if student is None:
            return RecognitionResult(
                recognized=False,
                student=None,
                similarity=best_match.similarity,
                confidence_band=eval_result.confidence_band,
                message="Matched student record not found.",
            )

        # Step 5b — Duplicate check
        now = self._attendance_now()
        check_date = on_date or now.date()
        now_time = self._plain_time(now.time())

        try:
            status = self._derive_status(now_time)
        except AttendanceWindowNotStartedError:
            log.info(
                "Attendance mark blocked before hostel check-in window",
                extra={"ctx_student_id": student_id, "ctx_date": str(check_date)},
            )
            return RecognitionResult(
                recognized=True,
                student=student,
                similarity=best_match.similarity,
                confidence_band=eval_result.confidence_band,
                message=ATTENDANCE_WINDOW_NOT_STARTED_MESSAGE,
                blocked_by_policy=True,
            )

        already_marked = await self._attendance_repo.has_record_for_date(
            student_id, on_date=check_date
        )
        if already_marked:
            log.info(
                "Attendance already marked — duplicate prevented",
                extra={"ctx_student_id": student_id, "ctx_date": str(check_date)},
            )
            return RecognitionResult(
                recognized=True,
                student=student,
                similarity=best_match.similarity,
                confidence_band=eval_result.confidence_band,
                message=f"Attendance already marked for {student.name} today.",
                already_marked=True,
            )

        # Step 7 — Mark attendance
        await self._attendance_repo.create(
            student_id=student_id,
            on_date=check_date,
            at_time=now_time,
            similarity_score=best_match.similarity,
            confidence_band=eval_result.confidence_band,
            status=status,
            device_id=device_id,
        )
        log.info(
            "Attendance marked",
            extra={
                "ctx_student_id": student_id,
                "ctx_student_name": student.name,
                "ctx_status": status.value,
                "ctx_similarity": round(best_match.similarity, 4),
                "ctx_date": str(check_date),
            },
        )
        return RecognitionResult(
            recognized=True,
            student=student,
            similarity=best_match.similarity,
            confidence_band=eval_result.confidence_band,
            message=f"Attendance marked for {student.name} "
                    f"({status.value}, similarity={best_match.similarity:.3f}).",
            attendance_marked=True,
        )

    # ── Manual attendance marking ──────────────────────────────────────────

    async def mark_manual(
        self,
        *,
        student_id: int,
        on_date: date_ | None = None,
        at_time: time_ | None = None,
        similarity_score: float = 1.0,
        confidence_band: ConfidenceBand = ConfidenceBand.HIGH,
        device_id: str | None = None,
    ) -> AttendanceMarkResponse:
        """
        Admin manual override for attendance marking.

        Mirrors the POST /attendance/mark endpoint's intent — an admin can
        backdate records or mark attendance for students who were present
        but not captured by the camera.

        Status is derived automatically from `at_time` using the same
        cutoff rule as the recognition pipeline.  The caller never supplies
        a status value.

        Returns:
            AttendanceMarkResponse with `already_marked=True` if a record
            already exists for (student_id, date).
        """
        now = self._attendance_now()
        check_date = on_date or now.date()
        check_time = self._plain_time(at_time or now.time())
        status = self._derive_status(check_time)

        already_marked = await self._attendance_repo.has_record_for_date(
            student_id, on_date=check_date
        )
        if already_marked:
            existing = await self._attendance_repo.get_for_student_on_date(
                student_id, check_date
            )
            log.info(
                "Manual mark skipped — already present",
                extra={"ctx_student_id": student_id, "ctx_date": str(check_date)},
            )
            return AttendanceMarkResponse(
                already_marked=True,
                record=AttendanceRead.model_validate(existing) if existing else None,
                message="Attendance already marked for this student today.",
            )

        record = await self._attendance_repo.create(
            student_id=student_id,
            on_date=check_date,
            at_time=check_time,
            similarity_score=similarity_score,
            confidence_band=confidence_band,
            status=status,
            device_id=device_id,
        )
        log.info(
            "Manual attendance marked",
            extra={
                "ctx_student_id": student_id,
                "ctx_status": status.value,
                "ctx_date": str(check_date),
            },
        )
        return AttendanceMarkResponse(
            already_marked=False,
            record=AttendanceRead.model_validate(record),
            message=f"Attendance marked successfully ({status.value}).",
        )

    # ── Absent generation (called by scheduler / cron at end-of-day) ──────

    async def generate_absent_records_for_date(
        self,
        target_date: date_,
    ) -> list[AttendanceRecord]:
        """
        Create ABSENT records for every registered student who has no attendance
        entry on `target_date`.

        This method is idempotent: if a record already exists (Present, Late,
        or a previously-generated Absent) for a student on that date it is
        silently skipped — no duplicate is ever created.

        Intended to be called by an APScheduler job or cron task at the end
        of each school day, e.g.:

            await svc.generate_absent_records_for_date(date.today())
            await session.commit()

        Args:
            target_date: The date for which to generate absent records.

        Returns:
            List of newly created AttendanceRecord rows (excludes skipped).
        """
        # All registered students — hard-delete is used, so every row in the
        # students table is a live student.
        active_students, _ = await self._student_repo.list(
            skip=0,
            limit=10_000,   # large upper bound; adjust if roster exceeds this
        )

        # End-of-day sentinel time — midnight represents "no scan occurred"
        absent_time = time_(0, 0, 0)

        created: list[AttendanceRecord] = []
        skipped = 0

        for student in active_students:
            already_has_record = await self._attendance_repo.has_record_for_date(
                student.id, on_date=target_date
            )
            if already_has_record:
                skipped += 1
                continue

            record = await self._attendance_repo.create(
                student_id=student.id,
                on_date=target_date,
                at_time=absent_time,
                similarity_score=0.0,
                confidence_band=ConfidenceBand.LOW,
                status=AttendanceStatus.ABSENT,
                device_id=None,
            )
            created.append(record)

        log.info(
            "Absent records generated",
            extra={
                "ctx_date": str(target_date),
                "ctx_created": len(created),
                "ctx_skipped": skipped,
            },
        )
        return created

    # ── Query / list ──────────────────────────────────────────────────────

    async def list_records(
        self, params: AttendanceQueryParams
    ) -> AttendanceListResponse:
        """
        Return a paginated list of attendance records matching the query params.

        Eagerly loads the student relationship to populate `student_name` and
        `student_code` in the response without N+1 queries.
        """
        skip = (params.page - 1) * params.page_size

        records = await self._attendance_repo.list(
            student_id=params.student_id,
            on_date=params.date,
            start_date=params.start_date,
            end_date=params.end_date,
            status=params.status,
            load_student=True,
            skip=skip,
            limit=params.page_size,
        )

        total = await self._attendance_repo.count(
            student_id=params.student_id,
            on_date=params.date,
            start_date=params.start_date,
            end_date=params.end_date,
            status=params.status,
        )

        items = [
            AttendanceReadWithStudent(
                id=r.id,
                student_id=r.student_id,
                date=r.date,
                time=r.time,
                similarity_score=r.similarity_score,
                confidence_band=r.confidence_band,
                status=r.status,
                device_id=r.device_id,
                created_at=r.created_at,
                student_name=r.student.name if r.student else None,
                student_code=r.student.student_code if r.student else None,
            )
            for r in records
        ]
        return AttendanceListResponse(
            total=total,
            page=params.page,
            page_size=params.page_size,
            items=items,
        )

    async def list_my_attendance(
        self,
        student_id: int,
        *,
        page: int = 1,
        page_size: int = 200,
    ) -> AttendanceListResponse:
        """
        Return attendance records scoped exclusively to `student_id`.

        This is the viewer-facing counterpart of list_records().  The
        student_id is sourced from the JWT by the endpoint — never from the
        request body or query params — so the isolation is enforced at the
        service boundary and cannot be bypassed by the client.
        """
        params = AttendanceQueryParams(
            student_id=student_id,
            page=page,
            page_size=page_size,
        )
        return await self.list_records(params)

    # ── Analytics ─────────────────────────────────────────────────────────

    async def get_summary(self) -> AnalyticsSummary:
        """
        Return top-level dashboard statistics.

        Matches the desktop app's stat card layout:
        Registered People | Today's Attendance | Total Records | Unknown Detections
        """
        total_students = await self._student_repo.count()
        attendance_date = self._attendance_summary_date()
        present_count = await self._attendance_repo.count(
            on_date=attendance_date,
            status=AttendanceStatus.PRESENT,
        )
        late_count = await self._attendance_repo.count(
            on_date=attendance_date,
            status=AttendanceStatus.LATE,
        )
        absent_count = await self._attendance_repo.count(
            on_date=attendance_date,
            status=AttendanceStatus.ABSENT,
        )
        total_records = await self._attendance_repo.count()
        unknown_count = await self._attendance_repo.count_unknown_detections()

        return AnalyticsSummary(
            total_students=total_students,
            today_attendance_count=present_count + late_count,
            total_attendance_records=total_records,
            unknown_detections_count=unknown_count,
            attendance_date=attendance_date,
            present_count=present_count,
            late_count=late_count,
            absent_count=absent_count,
        )

    async def get_daily(
        self, start_date: date_, end_date: date_
    ) -> DailyAttendanceResponse:
        """Return per-day attendance data for the daily bar chart."""
        rows = await self._attendance_repo.daily_counts(start_date, end_date)
        return DailyAttendanceResponse(
            start_date=start_date,
            end_date=end_date,
            points=[
                DailyAttendancePoint(
                    date=r["date"],
                    unique_students=r["unique_students"],
                    total_entries=r["total_entries"],
                )
                for r in rows
            ],
        )

    async def get_by_student(
        self,
        *,
        start_date: date_ | None = None,
        end_date: date_ | None = None,
        limit: int = 50,
    ) -> StudentAttendanceFrequencyResponse:
        """
        Return per-student attendance frequency enriched with student metadata.
        """
        rows = await self._attendance_repo.frequency_by_student(
            start_date=start_date, end_date=end_date, limit=limit
        )

        student_ids = [r["student_id"] for r in rows if r["student_id"]]
        students_by_id: dict[int, Student] = {}
        for sid in student_ids:
            s = await self._student_repo.get_by_id(sid)
            if s:
                students_by_id[sid] = s

        items = [
            StudentAttendanceFrequency(
                student_id=r["student_id"],
                student_name=(
                    students_by_id[r["student_id"]].name
                    if r["student_id"] in students_by_id
                    else "Unknown"
                ),
                student_code=(
                    students_by_id[r["student_id"]].student_code
                    if r["student_id"] in students_by_id
                    else ""
                ),
                days_present=r["days_present"],
                total_entries=r["total_entries"],
                first_seen=r["first_seen"],
                last_seen=r["last_seen"],
                avg_similarity=r["avg_similarity"],
            )
            for r in rows
            if r["student_id"] in students_by_id
        ]
        return StudentAttendanceFrequencyResponse(items=items)

    async def get_monthly(self, *, year: int | None = None) -> MonthlyAttendanceResponse:
        """Return monthly attendance totals for the monthly bar chart."""
        rows = await self._attendance_repo.monthly_counts(year=year)
        return MonthlyAttendanceResponse(
            points=[
                MonthlyAttendancePoint(month=r["month"], total_entries=r["total_entries"])
                for r in rows
            ]
        )
